version: '3'

services:
  # Nombre contenedor
  platzi-mongo:
    # image: platziapp
    build: .
    # Variables de entorno
    volumes:
      - ./platzi-api/:/usr/src/platzi-api
    ports:
      - '5000:5000'
